services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: carcare
      POSTGRES_PASSWORD: carcare
      POSTGRES_DB: carcare            # template DB name seed
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "carcare"]
      interval: 10s
      retries: 10

  migrate:
    volumes:
      - ./backend/src/Carmasters.Http.Api/appsettings.Secrets.json:/app/appsettings.Secrets.json:ro
    build:
      context: .
      dockerfile: backend/DbUp.Dockerfile
    depends_on:
      db:
        condition: service_healthy

  api:
    volumes:
      - ./backend/src/Carmasters.Http.Api/appsettings.Secrets.json:/app/appsettings.Secrets.json:ro
    build:
      context: .
      dockerfile: backend/Dockerfile
    depends_on:
      migrate:
        condition: service_completed_successfully
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
    ports:
      - "15567:15567"

  web:
    env_file:
      - frontend/.env
    build:
      context: .
      dockerfile: frontend/Dockerfile
    depends_on:
      - api
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:15567
    ports:
      - "3000:3000"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

volumes:
  dbdata:
