name: CI (monorepo)

on:
  pull_request:
    paths:
      - "backend/**"
      - "frontend/**"
  push:
    branches: [main]

jobs:
  backend:
    if: contains(github.event.head_commit.message, '[skip-backend]') == false
    uses: ./.gitea/workflows/backend-build.yml
    with:
      db-host: localhost
      db-password: ${{ secrets.DB_PASSWORD }}
      application-host: carcareco.app
      application-path: /opt/apps/
      ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      jwt-secret: ${{ secrets.JWT_SECRET }}
      consumer-secret: ${{ secrets.CONSUMER_SECRET }}
      application-host-user: debian
      smtp-host: ${{ secrets.SMTP_HOST }}
      smtp-port: 587
      smtp-password: ${{ secrets.SMTP_PASSWORD }}
      smtp-user: ${{ secrets.SMTP_USER }}
      cors-apphost: carcareco.app

  frontend:
    if: contains(github.event.head_commit.message, '[skip-frontend]') == false
    uses: ./.gitea/workflows/frontend-build.yml
    with:
      api-url: http://localhost:15567
      public-api-url: https://api.carcareco.app
      application-host: carcareco.app
      application-path: /opt/apps/
      ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      consumer-secret: ${{ secrets.CONSUMER_SECRET }}
      session-secret: ${{ secrets.SESSION_SECRET }}
      application-host-user: debian
